ActiveOrders = "ğŸ’¸ Active Orders"
Amount = "ğŸ“ˆ Amount"
AmountSection = "ğŸ’° Amount: "
Back = "Back"
BiggestGainer24h = "ğŸš€ Biggest Gainer 24h"
BiggestLoser24h = "ğŸ“‰ Biggest Loser 24h"
BiggestVolume24h = "ğŸ“Š Biggest Volume 24h"
BuyLimitOrder = "ğŸ“ˆ Buy"
CancelOrder = "Cancel Order"
ChangeDefaultLimitPair = "ğŸª™ Change Default Limit Pair"
ChangeLanguage = "ğŸŒ Change Language"
ChangePassword = "ğŸ”‘ Change Password"
Close = "Close"
ConfirmLimitOrder = "Confirm"
ConfirmOrder = "âœ… Confirm Order"
CreatePriceAlert = "ğŸ”” Create Price Alert"
CustomAmount = "Custom amount"
CustomToken = "Custom token"
DeletePriceAlert = "ğŸ”” Delete Price Alert"
DisablePassword = "ğŸ”’ Disable Password"
EnterCancelOrderId = "Enter the order ID to cancel"
FiftyDollar = "ğŸ’° $5"
FiveHundredDollar = "ğŸ’¶ $50"
HundredDollar = "ğŸ’¸ $10"
InlineAtom = "ATOM"
InlineInj = "INJ"
LimitOrder = "ğŸš€ Limit Order"
LimitOrderText = "ğŸ“Š Limit Orders\n\nBuy or Sell tokens automatically at your desired price.\n1. Choose to Buy or Sell.\n2. Choose the Token to Buy or Sell.\n3. Select the amount to Buy or Sell.\n4. Set your target buy or sell price.\n5. Click Create Order and Review, Confirm.\n\nTo manage or view unfilled orders, click Active Orders."
Menu = "Menu"
NoActiveOrders = "No active orders"
PayWith = "ğŸ’³ Pay With"
Price = "ğŸ’° Price"
PriceAlert = "ğŸ”” Price Alert"
RecipientNotSet = "Recipient not set"
RecipientSection = "ğŸ‘¤ Recipient: "
RecipientSet = "Recipient set"
SellLimitOrder = "ğŸ“‰ Sell"
Send = "Send"
SendToken = "ğŸ’¸ Send Token"
Settings = "âš™ Settings"
ShowAccount = "ğŸ‘¤ Show Account"
SpotOrder = "ğŸ“Š Spot Order"
TenDollar = "ğŸ’µ $1"
Token = "ğŸª™ Token"
TokenSection = "ğŸª™ Token: "
Transfer = "Transfer"
TwoHundredDollar = "ğŸª™ $20"
UpdatePriceAlert = "ğŸ”” Update Price Alert"
ViewBalances = "â„¹ View Balances"
ViewMarket = "ğŸ“ˆ View Market"
ViewPriceAlert = "ğŸ”” View Price Alert"
passwordAccepted = "Password accepted. You can perform your action again"
sessionExpired = "Session expired! Please enter your password"
