ActiveOrders = "ğŸ’¸ Active Orders"
Amount = "ğŸ“ˆ Amount"
AmountSection = "ğŸ’° Amount Section ğŸ’°"
Back = "Back"
BiggestGainer24h = "ğŸš€ Biggest Gainer 24h"
BiggestLoser24h = "ğŸ“‰ Biggest Loser 24h"
BiggestVolume24h = "ğŸ“Š Biggest Volume 24h"
BuyLimitOrder = "ğŸ“ˆ Buy"
CancelOrder = "Cancel Order"
ChangeDefaultLimitPair = "ğŸª™ Change Default Limit Pair"
ChangeLanguage = "ğŸŒ Change Language"
ChangePassword = "ğŸ”‘ Change Password"
Close = "Close"
ConfirmLimitOrder = "Confirm"
ConfirmOrder = "âœ… Confirm Order"
CustomAmount = "ğŸ›ï¸ Custom Amount"
CustomToken = "Custom Token"
DisablePassword = "ğŸ”’ Disable Password"
FiftyDollar = "ğŸ’° $5"
FiveHundredDollar = "ğŸ’¶ $50"
HundredDollar = "ğŸ’¸ $10"
InlineAtom = "ATOM"
InlineInj = "INJ"
LimitOrder = "ğŸš€ Limit Order"
Menu = "Menu"
PayWith = "ğŸ’³ Pay With"
Price = "ğŸ’° Price"
PriceAlert = "ğŸ”” Price Alert"
RecipientSection = "ğŸ“¨ Enter Recipient Address: ğŸ“¨ "
SellLimitOrder = "ğŸ“‰ Sell"
Send = "Send"
SendToken = "ğŸ’¸ Send Token"
Settings = "âš™ Settings"
ShowAccount = "ğŸ‘¤ Show Account"
SpotOrder = "ğŸ“Š Spot Order"
TenDollar = "ğŸ’µ $1"
Token = "ğŸª™ Token"
TokenSection = "ğŸ’  Token Section ğŸ’  "
TwoHundredDollar = "ğŸª™ $20"
ViewBalances = "â„¹ View Balances"
ViewMarket = "ğŸ“ˆ View Market"
passwordAccepted = "Password accepted. You can perform your action again"
sessionExpired = "Session expired! Please enter your password"
