[ActiveOrders]
hash = "sha1-bdc3d7a55cdb06ed1240d52e35c43b399a3bb7fb"
other = "ğŸ’¸ Lá»‡nh Ä‘ang hoáº¡t Ä‘á»™ng"

[AlertMessage]
hash = "sha1-6afd3d9597ae992e0f4bd064ab5e3cde9025e2c2"
other = "*ğŸš¨ ID Cáº£nh BÃ¡o:* {{.AlertID}}\n*ğŸ“ˆ {{.Name}} {{.Symbol}}/USDT*\nâ° ThÃ´ng bÃ¡o cho tÃ´i khi giÃ¡ *{{.Condition}} ${{.Value}}*\nğŸ’° GiÃ¡ hiá»‡n táº¡i báº±ng USD: ${{.CurrentPrice}}"

[AlertMessagePercentage]
hash = "sha1-f8185b94ac850bf3d20dd63fb911192dbfc121d9"
other = "*ğŸš¨ ID Cáº£nh bÃ¡o:* {{.AlertID}}\n*ğŸ“ˆ {{.Name}} {{.Symbol}}/USDT*\nâ° ThÃ´ng bÃ¡o cho tÃ´i khi giÃ¡ *{{.Condition}} {{.Value}}% trong 24h qua*\nğŸ’° GiÃ¡ hiá»‡n táº¡i theo USD: ${{.CurrentPrice}}"

[Amount]
hash = "sha1-2991f746c94ed74ad3a5cefe3d1580547242b954"
other = "ğŸ“ˆ Sá»‘ lÆ°á»£ng"

[AmountSection]
hash = "sha1-898d69dad63b5eb8335354acce673c1f04de10b4"
other = "ğŸ’° Sá»‘ lÆ°á»£ng: "

[Back]
hash = "sha1-b52b36b7269fbfc58ec24bb724691951a3decbe8"
other = "Quay láº¡i"

[BiggestGainer24h]
hash = "sha1-2fef0cf0f95fbb7e8c0494f1bfb05e5915909d65"
other = "ğŸš€ TÄƒng máº¡nh nháº¥t trong 24h"

[BiggestLoser24h]
hash = "sha1-2986b77d863b8e11a37fc8f717b07d68159228bf"
other = "ğŸ“‰ Giáº£m máº¡nh nháº¥t trong 24h"

[BiggestVolume24h]
hash = "sha1-601fe41fd51d7d18b4a0e0c4a136c53f8dae1e1a"
other = "ğŸ“Š Khá»‘i lÆ°á»£ng giao dá»‹ch lá»›n nháº¥t trong 24h"

[BuyLimitOrder]
hash = "sha1-2ad43f233e8159b4bdfcb28004c75bf0d6910c87"
other = "ğŸ“ˆ Mua"

[CancelOrder]
hash = "sha1-87125442f43bbc46421d0b1ab33926a65ce15170"
other = "Há»§y Ä‘Æ¡n hÃ ng"

[ChangeDefaultLimitPair]
hash = "sha1-1a8d9cf49c4881e5db17f4f5a0ece7db51759d87"
other = "ğŸª™ Thay Ä‘á»•i cáº·p giá»›i háº¡n máº·c Ä‘á»‹nh"

[ChangeLanguage]
hash = "sha1-dd2b5dda42509ad3af1bd2a139b6fdc3152152ad"
other = "ğŸŒ Thay Ä‘á»•i ngÃ´n ngá»¯"

[ChangePassword]
hash = "sha1-b5b43b2ebbddd619bf55a994d4e7d29026f67969"
other = "ğŸ”‘ Äá»•i máº­t kháº©u"

[Close]
hash = "sha1-bbfa773e5a63a5ea58c9b6207e608ca0120e592a"
other = "ÄÃ³ng"

[ConfirmLimitOrder]
hash = "sha1-04a212215ef9fbf686d280802eb81ee7a6e681cd"
other = "XÃ¡c nháº­n"

[ConfirmOrder]
hash = "sha1-1c45b72a1a9c0f4ecf7b56ee74e7d85096203c21"
other = "âœ… XÃ¡c nháº­n Ä‘Æ¡n hÃ ng"

[CreatePriceAlert]
hash = "sha1-b79b0447bb32a72cea8c9a83b323f631a7ed4213"
other = "ğŸ”” Táº¡o cáº£nh bÃ¡o giÃ¡"

[CustomAmount]
hash = "sha1-f7219236a0f86266f4daad5fceab2b6bb447b8eb"
other = "Tuá»³ chá»n"

[CustomToken]
hash = "sha1-5cca3ae612fa2b762cf2f30c637a8463fbad407a"
other = "Tuá»³ chá»n"

[DeletePriceAlert]
hash = "sha1-3dec3258536373474bc4c76994e917e584f98081"
other = "ğŸ”” XoÃ¡ cáº£nh bÃ¡o giÃ¡"

[DisablePassword]
hash = "sha1-64727003c8df52d45498d635de7bbd3b10db96da"
other = "ğŸ”’ Táº¯t máº­t kháº©u"

[EnterCancelOrderId]
hash = "sha1-98b8bd36a927261d0f58a24e430c1950c58c159a"
other = "Nháº­p mÃ£ lá»‡nh cáº§n há»§y"

[FiftyDollar]
hash = "sha1-39f38044aff76f8e2a77d0fdb553b9237dc01eed"
other = "ğŸ’° $5"

[FiveHundredDollar]
hash = "sha1-8458ab3e370a1b32e58f7787df7145e9e6ba6f15"
other = "ğŸ’¶ $50"

[HundredDollar]
hash = "sha1-4dad1967fb839aeb7c202cd3b4eb2169ab5864cf"
other = "ğŸ’¸ $10"

[InlineAtom]
hash = "sha1-cae061a530cef71c477f974034de1fd1d9b43ecb"
other = "ATOM"

[InlineInj]
hash = "sha1-3be5bffea6848d347c762ee093a71d9ac12565d2"
other = "INJ"

[LimitOrder]
hash = "sha1-e3a98c0c9bf1d28f6dcfe60acf7d48dfc0f55720"
other = "ğŸš€ ÄÆ¡n hÃ ng giá»›i háº¡n"

[LimitOrderText]
hash = "sha1-61e4865c6eb840015a3a70d5a9e493b5e2e4cc53"
other = "Lá»‡nh Giá»›i Háº¡n\n\nTá»± Ä‘á»™ng Mua hoáº·c BÃ¡n token á»Ÿ má»©c giÃ¡ mong muá»‘n cá»§a báº¡n.\n1. Chá»n Mua hoáº·c BÃ¡n.\n2. Chá»n Token Ä‘á»ƒ Mua hoáº·c BÃ¡n.\n3. Chá»n sá»‘ lÆ°á»£ng Ä‘á»ƒ Mua hoáº·c BÃ¡n.\n4. Äáº·t giÃ¡ mua hoáº·c bÃ¡n má»¥c tiÃªu cá»§a báº¡n.\n5. Nháº¥p vÃ o Táº¡o Lá»‡nh vÃ  Xem xÃ©t, XÃ¡c nháº­n.\n\nÄá»ƒ quáº£n lÃ½ hoáº·c xem cÃ¡c lá»‡nh chÆ°a Ä‘Æ°á»£c thá»±c hiá»‡n, hÃ£y nháº¥p vÃ o Lá»‡nh Äang Hoáº¡t Äá»™ng."

[Menu]
hash = "sha1-57f5f5efbc5990f5230aa95359042338b856707b"
other = "Menu"

[NoActiveOrders]
hash = "sha1-03574d967abbc2489931876ec919a0f382c33fa4"
other = "KhÃ´ng cÃ³ lá»‡nh nÃ o Ä‘ang hoáº¡t Ä‘á»™ng"

[PayWith]
hash = "sha1-3042edc58ff225bb170f36f3b6b7074dbb4f41e6"
other = "ğŸ’³ Thanh toÃ¡n báº±ng"

[Price]
hash = "sha1-aa897c5b15197311bf5c27a8a9d03307a4b450c7"
other = "ğŸ’° GiÃ¡"

[PriceAlert]
hash = "sha1-e227d2d2e0720d944f51645187fe9d78be5af6c3"
other = "ğŸ”” Cáº£nh bÃ¡o giÃ¡"

[RecipientNotSet]
hash = "sha1-df3042b266fd09435496954dec2f52cef7310502"
other = "VÃ­ nháº­n chÆ°a Ä‘Æ°á»£c thiáº¿t láº­p"

[RecipientSection]
hash = "sha1-296dd10c844bdd1cfd2750bed3b126916a3e9645"
other = "ğŸ‘¤ VÃ­ nháº­n: "

[RecipientSet]
hash = "sha1-8143e5cecade0c4f38472727a5a34b7e414ee705"
other = "VÃ­ nháº­n Ä‘Ã£ Ä‘Æ°á»£c thiáº¿t láº­p"

[SellLimitOrder]
hash = "sha1-501239964b7b655a71bcc8189720a43a93ba784f"
other = "ğŸ“‰ BÃ¡n"

[Send]
hash = "sha1-9bc2575c3930437e80555f78757b783c842e8e66"
other = "Gá»­i"

[SendToken]
hash = "sha1-42081cf4a6ea243a9e4078e2b24a55a5d00f481c"
other = "ğŸ’¸ Gá»­i token"

[Settings]
hash = "sha1-9249b284db863d58f6e68e37edcc28ba67a79006"
other = "âš™ CÃ i Ä‘áº·t"

[ShowAccount]
hash = "sha1-5f259162ae66a5ccf200e172a4df9a7d86a8af9f"
other = "ğŸ‘¤ Xem tÃ i khoáº£n"

[SpotOrder]
hash = "sha1-a70f4423b196325aac67abc795ea22428a485636"
other = "ğŸ“Š Lá»‡nh giao dá»‹ch ngay"

[TenDollar]
hash = "sha1-53afc36e20e5dac5105f243473da2e69591afc3a"
other = "ğŸ’µ $1"

[Token]
hash = "sha1-3728b0d79c2c7d16c99b8006c30cf00d715fd180"
other = "ğŸª™ Token"

[TokenSection]
hash = "sha1-e8973995b626fd397c4ad8ef7b028af4a2c6a26c"
other = "ğŸª™ Token: "

[Transfer]
hash = "sha1-cbb4cc49824bf79827cde838e005848027ca0a38"
other = "Chuyá»ƒn"

[TwoHundredDollar]
hash = "sha1-f5357181a7d93f85cbcb4bb7d0ab154c64045657"
other = "ğŸª™ $20"

[UpdatePriceAlert]
hash = "sha1-cfd95e32b0492574ae4723830b94639f5596fb55"
other = "ğŸ”” Sá»­a cáº£nh bÃ¡o giÃ¡"

[ViewBalances]
hash = "sha1-ad52c60627ecd8004c1b6d4e83afcac0a911555e"
other = "â„¹ Xem sá»‘ dÆ°"

[ViewMarket]
hash = "sha1-ee24065e4e2510436cf366e16647929a4f5937cf"
other = "ğŸ“ˆ Xem thá»‹ trÆ°á»ng"

[ViewPriceAlert]
hash = "sha1-7987b7e03f4e2ee162931e6a29c02dac556f141c"
other = "ğŸ”” Xem cáº£nh bÃ¡o giÃ¡"

[passwordAccepted]
hash = "sha1-d8c53c910dbbfef2234af84a2f36a05debbc5294"
other = "Máº­t kháº©u chÃ­nh xÃ¡c. Báº¡n Ä‘Ã£ Ä‘Äƒng nháº­p thÃ nh cÃ´ng!"

[sessionExpired]
hash = "sha1-6e0d3fabd35e7f64b800067c3b8607b87059c7c4"
other = "PhiÃªn lÃ m viá»‡c cá»§a báº¡n Ä‘Ã£ háº¿t háº¡n. Vui lÃ²ng Ä‘Äƒng nháº­p láº¡i."
