[AlertMessagePercentage]
hash = "sha1-f8185b94ac850bf3d20dd63fb911192dbfc121d9"
other = "*ğŸš¨ ID Cáº£nh bÃ¡o:* {{.AlertID}}\n*ğŸ“ˆ {{.Name}} {{.Symbol}}/USDT*\nâ° ThÃ´ng bÃ¡o cho tÃ´i khi giÃ¡ *{{.Condition}} {{.Value}}% trong 24h qua*\nğŸ’° GiÃ¡ hiá»‡n táº¡i theo USD: ${{.CurrentPrice}}"
